### ISSUE TITLE
How to change style property of highlighted tag

### ISSUE THREAD

**Issue by SahilDhingraa** [smhaley/react-text-annotate-blend#12]
![image](https://github.com/smhaley/react-text-annotate-blend/assets/92306979/1119cc19-749e-4a05-810e-c6987b9ec034)
in the image you can see the span tag with the yellow highlighted colour. but I want to change it's padding to 0 because it's breaking word.

**Comment by smhaley** [comment]
With the `TextAnnotate`  component you can pass a className which would allow for the padding to be removed from the html `mark` element, 

However there is a bug. I will update, do a release, and provide an example this week.

**Comment by smhaley** [comment]
This took a long time, but it is now addressed with release v `1.2.0` -- which is available on npm

The release adds four new optional props to both `<TextAnnotateBlend/>` `<TextAnnotate/>`.

Take a look at props in the [docs](https://smhaley.github.io/react-text-annotate-blend/) or the [changelog](https://github.com/smhaley/react-text-annotate-blend/blob/main/changelog.md).

There are now two ways to remove the padding -- or overrides styles:
 - 1: `markClassName`: pass a class that you want directly on the `mark` 
 - 2: `markStyle`: pass a react style obj directly to the mark.

for example:
```
<TextAnnotateBlend
    markStyle = {{padding:0}}
    ...
    />
```

**Comment by SahilDhingraa** [comment]
great, thanks!

**Comment by smhaley** [comment]
No problem. Sorry I did not get to it sooner!
