### ISSUE TITLE
How to limit to 1 highlight

### ISSUE THREAD

**Issue by psologub** [smhaley/react-text-annotate-blend#15]
I would like to only be able to highlight one selection at a time. Is this possible?

**Comment by smhaley** [comment]
In terms of the the user highlighting, I think not. But in terms of the stored highlights that are represented back on the screen, yes.

Just limit what `handleChange` does, here.

A very minimum example would be 


```
    const [value, setValue] = React.useState([]);

  const handleChange = (annotationSet: AnnotateTag[]) => {
   !value.length && setValue(annotationSet);
  };
```

The rest would follow here: https://github.com/smhaley/react-text-annotate-blend/blob/main/examples/interactive-annotate.tsx

Is this what you mean?

**Comment by smhaley** [comment]
@psologub is it okay to close this?

**Comment by psologub** [comment]
yes, thank you!
