### ISSUE TITLE
Duplicate key when different annotations have same start and end

### ISSUE THREAD

**Issue by remoun** [smhaley/react-text-annotate-blend#16]
I have an app where multiple annotation types can overlap. When different annotation types overlap exactly (same start and end), `react-text-annotate-blend` ends up displaying that word multiple times due to duplicate keys, since [it uses the start and end indexes as the key](https://github.com/smhaley/react-text-annotate-blend/blob/269b1e7613def796d9f661949df27e76ab50a911/src/components/Annotator.tsx#L54). Can we please include the `tag` or `color` in the `SplitTag key`?

**Comment by smhaley** [comment]
The blending should be rectified by `generateSplits`. In other words the two tags that are overlapping should be handled. 

I am assuming you are using  `TextAnnotateBlend`.  The assumption with `TextAnnotate` is that there cannot be an overlap.
Can you provide a minimum example and/or a screenshot?

**Comment by smhaley** [comment]
If you are using `<TextAnnotate/>` you most certainly will get a dupe. This should result in a [console error](https://github.com/smhaley/react-text-annotate-blend/blob/main/src/components/utils/utils.ts#L107). This is because `TextAnnotate` uses the `strict` flag of `generateSplits`.
 
 A quick example can be seen in the live demo of `<TextAnnotate/>` 
 
  1. https://smhaley.github.io/react-text-annotate-blend/
  2. click on `Live Demo` under `<TextAnnotate/>`
  3. Change the initial state to: 
  ```
      const [value, setValue] = React.useState(  [{
    start: 0,
    end: 3,
    tag: "tagC",
    color: "#4b46cd",
  },
  {
    start: 0,
    end: 3,
    tag: "tagB",
    color: "#42f5f5",
  }]);
  ```
  4. See the below result: 
  
![image](https://github.com/smhaley/react-text-annotate-blend/assets/12714199/75d3d4a1-19b7-4fab-b0d3-fa361a5b295b)


This is expected behavior as this is not a valid annotation. Only `<TextAnnotateBlend/>` allows overlapping.

**Comment by remoun** [comment]
Yes, I'm using `TextAnnotateBlend`. Here's a repro: https://codesandbox.io/p/sandbox/eloquent-snow-l2y4jm?file=%2Fsrc%2FApp.tsx

It turns out that having a second tag with the same start and end indexes blends OK, but adding a third tag with the same start and end triggers the error I'm seeing.

I have 3 independently triggering annotation types that might tag the same word, and that's when I see this error: "Warning: Encountered two children with the same key, `0-3`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version."

**Comment by smhaley** [comment]
I see. The uniqueness of the key will not resolve this issue. If you dig into [blend.ts](https://github.com/smhaley/react-text-annotate-blend/blob/main/src/components/utils/blend.ts) it may be clear how it works under the hood and why your proposed solution will not do anything to resolve the issue. An additional issue with you solution is that it makes too many assumptions on what a tag is -- only a `start` and `end` are required -- but it would have not net change regarding your issue.. 

As is, a core assumption to `TextAnnotateBlend` is that the max number of overlapping tags is two. 
This fact is reinforced in that the software prohibits the constructions of greater than two overlapping tags. I am assuming your tags are coming from something external. 

It looks like I inadvertently removed this from the docs a while back. I'll add this back into the readme and the docs. 
I removed this: `TextAnnotateBlend only supports a single overlap of annotations.` by mistake.

I think we can resolve this issue and close the PR given this. 
What do you think?

**Comment by remoun** [comment]
OK, thanks for the response
